name: Windows Germany RDP

on:
  workflow_dispatch:
    inputs:
      ngrok_token:
        description: 'Paste your Ngrok Authtoken'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install Ngrok
      shell: powershell
      run: |
        Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip
        Move-Item .\ngrok.exe C:\ngrok.exe

    - name: Start RDP & Configure
      shell: powershell
      run: |
        net user Administrator MyNewPassword123!
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Enable-PSRemoting -Force

    - name: Start Ngrok Tunnel (Germany)
      shell: powershell
      run: |
        C:\ngrok.exe authtoken "${{ github.event.inputs.ngrok_token }}"
        Start-Process -NoNewWindow -FilePath "C:\ngrok.exe" -ArgumentList "tcp --region=eu 3389"
        Start-Sleep -Seconds 10

    - name: Show RDP Info
      shell: powershell
      run: |
        Invoke-WebRequest -UseBasicParsing -Uri "http://127.0.0.1:4040/api/tunnels" > tunnel.json
        Get-Content tunnel.json
        echo "Username: Administrator"
        echo "Password: MyNewPassword123!"
